'class Library:' 
'    def __init__(self, name):' 
'        self.name = name' 
'        self.books = []' 
'        self.patrons = []' 
'' 
'    def add_book(self, book):' 
'        self.books.append(book)' 
'' 
'    def remove_book(self, book):' 
'        if book in self.books:' 
'            self.books.remove(book)' 
'' 
'    def add_patron(self, patron):' 
'        self.patrons.append(patron)' 
'' 
'    def remove_patron(self, patron):' 
'        if patron in self.patrons:' 
'            self.patrons.remove(patron)' 
'' 
'    def list_books(self):' 
'        books_str = "Books in Library \'" + self.name + "\'\n"' 
'        for book in self.books:' 
'            books_str += str(book) + "\n"' 
'        print(books_str)' 
'' 
'    def list_patrons(self):' 
'        patrons_str = "Patrons in Library \'" + self.name + "\'\n"' 
'        for patron in self.patrons:' 
'            patrons_str += str(patron) + "\n"' 
'        print(patrons_str)' 
