'from Person import Person\n\nclass Patron(Person):' 
'    def __init__(self, name, person_id):' 
'        super().__init__(name, person_id)' 
'        self.borrowed_books = []' 
'' 
'    def borrow_book(self, book):' 
'        self.borrowed_books.append(book)' 
'' 
'    def return_book(self, book):' 
'        if book in self.borrowed_books:' 
'            self.borrowed_books.remove(book)' 
'' 
'    def __str__(self):' 
'        return "Patron: " + self.name + " (ID: " + self.person_id + ")"' 
